export enum CharacterClass {
    'BERSERKER', 'PALADIN', 'GUNLANCER', 'DESTROYER', 'SLAYER', 'STRIKER', 'WARDANCER', 'SCRAPPER', 'SOULFIST', 'GLAVIER', 'MACHINIST',
	'GUNSLINGER', 'ARTILLERIST', 'DEADEYE', 'SHARPSHOOTER', 'ARCANIST', 'SUMMONER', 'BARD', 'SORCERESS', 'REAPER', 'SHADOWHUNTER',
	'DEATHBLADE', 'ARTIST', 'AEROMANCER'
}