version: "1"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  backend:
    image: gemtries-backend
    environment:
      - DB_URL=jdbc:postgresql://db:5432/
    ports:
      - "8080:8080"
    depends_on:
      - db